Public Module mdlGLobal
    Public Enum PIZZA_ITEM_TYPE
        PIZZA_ITEM_TYPE_NOTHING = -1
        PIZZA_ITEM_TYPE_PIZZA = 0
        PIZZA_ITEM_TYPE_BREADSTICK = 1
        PIZZA_ITEM_TYPE_SODA = 2
        PIZZA_ITEM_TYPE_PASTA = 3
    End Enum

    Public Enum PIZZA_ITEM_TOPPINGS
        PIZZA_ITEM_TOPPINGS_SAUSAGE = 0
        PIZZA_ITEM_TOPPINGS_PEPPERONI = 1
        PIZZA_ITEM_TOPPINGS_HAM = 2
        PIZZA_ITEM_TOPPINGS_PINEAPPLE = 3
        PIZZA_ITEM_TOPPINGS_BACON = 4
        PIZZA_ITEM_TOPPINGS_CHEESE = 5
        PIZZA_ITEM_TOPPINGS_GREENPEPPER = 6
        PIZZA_ITEM_TOPPINGS_NACHOCHEESE = 7
        PIZZA_ITEM_TOPPINGS_RANCH = 8
        PIZZA_ITEM_TOPPINGS_VANILLAICING = 9
    End Enum

    Public Enum PIZZA_ITEM_SIZE
        PIZZA_ITEM_SIZE_PERSONAL = 0
        PIZZA_ITEM_SIZE_SMALL = 1
        PIZZA_ITEM_SIZE_MEDIUM = 2
        PIZZA_ITEM_SIZE_LARGE = 3
        PIZZA_ITEM_SIZE_XLARGE = 4
        PIZZA_ITEM_SIZE_20OZ = 5
        PIZZA_ITEM_SIZE_2LITER = 6
    End Enum
    Public Enum PIZZA_ITEM_SPECIALTY_TYPE
        PIZZA_ITEM_SPECIALTY_TYPE_BREADSTICKS_REGULAR = 0
        PIZZA_ITEM_SPECIALTY_TYPE_BREADSTICKS_CHEESY = 1
        PIZZA_ITEM_SPECIALTY_TYPE_BREADSTICKS_CINNAMON = 2
        PIZZA_ITEM_SPECIALTY_TYPE_PIZZA_HANDTOSSED = 3
        PIZZA_ITEM_SPECIALTY_TYPE_PIZZA_THINCRUST = 4
        PIZZA_ITEM_SPECIALTY_TYPE_PIZZA_DEEPDISH = 5
        PIZZA_ITEM_SPECIALTY_TYPE_PIZZA_LAYEREDCHEESE = 6
        PIZZA_ITEM_SPECIALTY_TYPE_PASTA_MARINARA = 7
        PIZZA_ITEM_SPECIALTY_TYPE_PASTA_ALFREDO = 8
        PIZZA_ITEM_SPECIALTY_TYPE_PASTA_ITALIAN = 9
        PIZZA_ITEM_SPECIALTY_TYPE_SODA_COKE = 10
        PIZZA_ITEM_SPECIALTY_TYPE_SODA_DCOKE = 11
        PIZZA_ITEM_SPECIALTY_TYPE_SODA_SPRITE = 12
        PIZZA_ITEM_SPECIALTY_TYPE_SODA_MELLOYELLOW = 13
        PIZZA_ITEM_SPECIALTY_TYPE_SODA_ROOTBEER = 14
        PIZZA_ITEM_SPECIALTY_TYPE_SODA_LEMONAIDE = 15
    End Enum
End Module
